### ISSUE TITLE
Install Tutorial Please

### ISSUE THREAD

**Issue by feralsja** [vudung45/HLS-GoogleDrive#5]
Hai Master Please add tutorial install

THANKS

**Comment by vudung45** [comment]
@feralsja  this repo is still under development. You can take a look at the code for educational purposes.
Since this project is developed to be production ready, people can easily just download and start monetizing it. That seems a bit too easy, isn't it? I don't think I will provide any support to setup the project anytime soon in the future.

Thanks

**Comment by theraw** [comment]
@vudung45 then why do you leave this public? github private repos are free now you can keep it for yourself. Ppl like this who's asking you. Means he/she has no idea at all ppl who know to monetize also know how to set it up no need for questions meaning what you're doing is just giving your code to those who monetize and new ppl who have not much idea are without answers.

Clap Clap Clap.

**Comment by ghost** [comment]
@theraw can you fork and add wiki if you know how it works? thanks

**Comment by vudung45** [comment]
@theraw Those who have done their research could definitely profit from this repo.
I'm also publishing it for self-use as well.
Will probably setup a proper guide if I have time in the future.

**Comment by ghost** [comment]
looking at the code on the file "files_manager/uploader.js" we can upload a raw mp4 but that is not implemented in the front-end right ?

so basically we need to code our own front end?

**Comment by theraw** [comment]
@Hanoosh https://github.com/ParveenBhadooOfficial/Bhadoo-Drive-Index use this. It uses cloudflare workers you don't even need a hosting.

demo https://calm-snow-b697.testings.workers.dev/0:/hls/test/
